const carList = [
  {
    reg_no: "GC-5951",
    fleet: "General",
    brand: "Suzuki Alto - Premium",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "Gray",
    mileage: "7500 KM",
    daily_rate: "2500",
    freeKM_perDay: "100",
    monthly_rate: "64350",
    freeKM_perMonth: "2400",
    price_perExtraKM: "30.00",
  },
  {
    reg_no: "PC-5951",
    fleet: "Premium",
    brand: "Toyota Corolla Axio",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "White",
    mileage: "8000 KM",
    daily_rate: "5500",
    freeKM_perDay: "100",
    monthly_rate: "120330",
    freeKM_perMonth: "2400",
    price_perExtraKM: "49.50",
  },
  {
    reg_no: "LC-5951",
    fleet: "Luxury",
    brand: "BMW i8",
    passengers: "2",
    transmission: "Auto",
    fuel: "Gasoline",
    color: "Black",
    mileage: "5000 KM",
    daily_rate: "18000",
    freeKM_perDay: "100",
    monthly_rate: "300000",
    freeKM_perMonth: "2400",
    price_perExtraKM: "100.00",
  },
];

export default carList;
