const generalCarList = [
  {
    reg_no: "GC-5951",
    fleet: "General",
    brand: "Suzuki Alto - Premium",
    passengers: "4",
    transmission: "Manual",
    fuel: "Petrol",
    color: "Gray",
    mileage: "7500",
    daily_rate: "2500",
    freeKM_perDay: "100",
    monthly_rate: "64350",
    freeKM_perMonth: "2400",
    price_perExtraKM: "30.00",
  },
  {
    reg_no: "GC-5952",
    fleet: "General",
    brand: "Suzuki Alto K10 ",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "White",
    mileage: "8100",
    daily_rate: "3000",
    freeKM_perDay: "100",
    monthly_rate: "71390",
    freeKM_perMonth: "2400",
    price_perExtraKM: "35.00",
  },
  {
    reg_no: "GC-5953",
    fleet: "General",
    brand: "Suzuki Celerio",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "Black",
    mileage: "4000",
    daily_rate: "3300",
    freeKM_perDay: "100",
    monthly_rate: "77220",
    freeKM_perMonth: "2400",
    price_perExtraKM: "35.00",
  },
  {
    reg_no: "GC-5954",
    fleet: "General",
    brand: "Perodua (Daihatsu) Axia",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "Black",
    mileage: "4400",
    daily_rate: "3800",
    freeKM_perDay: "100",
    monthly_rate: "90200",
    freeKM_perMonth: "2400",
    price_perExtraKM: "35.00",
  },
  {
    reg_no: "GC-5955",
    fleet: "General",
    brand: "Toyota Prius C / Aqua",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "White",
    mileage: "4800",
    daily_rate: "5000",
    freeKM_perDay: "100",
    monthly_rate: "110330",
    freeKM_perMonth: "2400",
    price_perExtraKM: "49.50",
  },
];

export default generalCarList;
