const luxuryCarList = [
  {
    reg_no: "LC-5951",
    fleet: "Luxury",
    brand: "Toyota Premio",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "White",
    mileage: "9600",
    daily_rate: "10000",
    freeKM_perDay: "100",
    monthly_rate: "227150",
    freeKM_perMonth: "2400",
    price_perExtraKM: "85.00",
    img1: "../../assets/images/Luxury/ToyotaPremio/front.jpeg",
    img2: "../../assets/images/Luxury/ToyotaPremio/side.jpeg",
    img3: "../../assets/images/Luxury/ToyotaPremio/side2.jpeg",
    img4: "../../assets/images/Luxury/ToyotaPremio/dashboard.png",
  },
  {
    reg_no: "LC-5952",
    fleet: "Luxury",
    brand: "Mercedes",
    passengers: "2",
    transmission: "Auto",
    fuel: "Petrol",
    color: "White",
    mileage: "8100",
    daily_rate: "18000",
    freeKM_perDay: "100",
    monthly_rate: "300000",
    freeKM_perMonth: "2400",
    price_perExtraKM: "100.00",
    img1: "../../assets/images/Luxury/Mercedes/front.jpg",
    img2: "../../assets/images/Luxury/Mercedes/side.jpg",
    img4: "../../assets/images/Luxury/Mercedes/dashboard.jpg",
    img3: "../../assets/images/Luxury/Mercedes/back.jpg",
  },
  {
    reg_no: "LC-5953",
    fleet: "Luxury",
    brand: "BMW i8 ",
    passengers: "2",
    transmission: "Auto",
    fuel: "Petrol",
    color: "Black",
    mileage: "4300",
    daily_rate: "18000",
    freeKM_perDay: "100",
    monthly_rate: "300000",
    freeKM_perMonth: "2400",
    price_perExtraKM: "100.00",
    img1: "../../assets/images/Luxury/BMW/front.jpg",
    img2: "../../assets/images/Luxury/BMW/back.jpg",
    img3: "../../assets/images/Luxury/BMW/side1.jpg",
    img4: "../../assets/images/Luxury/BMW/side2.jpg",
  },
];

export default luxuryCarList;
