const luxuryCarList = [
  {
    reg_no: "LC-5951",
    fleet: "Luxury",
    brand: "Toyota Premio",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "White",
    mileage: "9600 KM",
    daily_rate: "10000",
    freeKM_perDay: "100",
    monthly_rate: "227150",
    freeKM_perMonth: "2400",
    price_perExtraKM: "85.00",
  },
  {
    reg_no: "LC-5952",
    fleet: "Luxury",
    brand: "Mercedes",
    passengers: "2",
    transmission: "Auto",
    fuel: "Petrol",
    color: "White",
    mileage: "8100 KM",
    daily_rate: "18000",
    freeKM_perDay: "100",
    monthly_rate: "300000",
    freeKM_perMonth: "2400",
    price_perExtraKM: "100.00",
  },
  {
    reg_no: "LC-5953",
    fleet: "Luxury",
    brand: "BMW i8 ",
    passengers: "2",
    transmission: "Auto",
    fuel: "Petrol",
    color: "Black",
    mileage: "4300 KM",
    daily_rate: "18000",
    freeKM_perDay: "100",
    monthly_rate: "300000",
    freeKM_perMonth: "2400",
    price_perExtraKM: "100.00",
  },
];

export default luxuryCarList;
