export const styleSheet = {
  avatar__container: {
    // border: "2px solid red",
    width: "12rem",
    height: "12rem",
    margin: "auto",
    marginBottom: "30px",
    // background: "linear-gradient(25deg,red,blue)",
    background: "linear-gradient(25deg,#0071bd,#2babe4)",
    borderRadius: "50%",
    marginTop: "-35vh",
    position: "absolute",
    right: "0px",
    left: "0px",
    zIndex: "3",
    // position: "sticky",
    // top: "0",
  },
  avatar__img: {
    // border: "2px solid red",
    // border: "2px blur",
    height: "93%",
    width: "93%",
    borderRadius: "50%",
    margin: "6px 7px",
  },
};
