const premiumCarList = [
  {
    reg_no: "PC-5951",
    fleet: "Premium",
    brand: "Toyota Corolla Axio/ NZE141",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "White",
    mileage: "7500",
    daily_rate: "5500",
    freeKM_perDay: "100",
    monthly_rate: "120330",
    freeKM_perMonth: "2400",
    price_perExtraKM: "49.50",
  },
  {
    reg_no: "PC-5952",
    fleet: "Premium",
    brand: "Perodua Bezza Prime Sedan",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "White",
    mileage: "8100",
    daily_rate: "5500",
    freeKM_perDay: "100",
    monthly_rate: "120330",
    freeKM_perMonth: "2400",
    price_perExtraKM: "49.50",
  },
  {
    reg_no: "PC-5953",
    fleet: "Premium",
    brand: "Toyota Allion NZT 260",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "Black",
    mileage: "4300",
    daily_rate: "5800",
    freeKM_perDay: "100",
    monthly_rate: "155760",
    freeKM_perMonth: "2400",
    price_perExtraKM: "60.00",
  },
  {
    reg_no: "PC-5954",
    fleet: "Premium",
    brand: "Toyota Axio NKR 165",
    passengers: "4",
    transmission: "Auto",
    fuel: "Petrol",
    color: "Blue",
    mileage: "6400",
    daily_rate: "6000",
    freeKM_perDay: "100",
    monthly_rate: "175230",
    freeKM_perMonth: "2400",
    price_perExtraKM: "65.00",
  },
];

export default premiumCarList;
